[workspace]
channels = ["conda-forge"]
description = "Add a short description here"
name = "psydk"
platforms = ["win-64", "osx-arm64"]
version = "0.1.0"

[tasks]
"build-py" = { cwd = "crates/psydk", cmd = "maturin build -r", env = { CARGO_BUILD_TARGET = "aarch64-apple-darwin"} }

"build-py-ios" = { cwd = "crates/psydk", env = { FORCE_SKIA_BUILD="1", PYTHON_VERSION = "3.10", PYTHONDIR = "$PIXI_PROJECT_ROOT/psydk/dependencies/build_helpers/iphoneos/" }, cmd = "dependencies/build_helpers/build_ios.sh" }
"build-docs" = "sphinx-build -M html docs/source/ docs/build/ -W -a -j auto -n --keep-going"

"dev-py" = { cwd = "crates/psydk", cmd = "maturin develop" }

# "launcher-build-py-ios" = { cwd = "psydk-launcher", env = { PYTHON_VERSION = "3.10", PYTHONDIR = "$PIXI_PROJECT_ROOT/psydk/dependencies/build_helpers/iphoneos/" }, cmd = "dependencies/build_helpers/build_ios.sh" }

[dependencies]
python = "3.12.*"
pixi-pycharm = ">=0.0.8,<0.0.9"
pip = ">=26.0.1,<27"
mkdocs = ">=1.6.1,<2"
mkdocs-material = ">=9.6.5,<10"
mkdocstrings-python = ">=1.16.1,<2"
griffe-inherited-docstrings = ">=1.1.1,<2"
pymunk = ">=6.10.0,<7"
emsdk = ">=3.1.46,<4"
numpy = ">=2.2.3,<3"
pandas = ">=2.2.3,<3"
sphinx = ">=8.1.3,<9"
sphinx-tabs = ">=3.4.1,<4"
python-lsp-server = ">=1.12.2,<2"
clang-16 = ">=16.0.6,<17"

[pypi-dependencies]
maturin = ">=1.12.6, <2"
cibuildwheel = ">=3.3.0, <4"
sphinxcontrib-napoleon = ">=0.7, <0.8"
sphinx-rtd-theme = ">=3.0.2, <4"
pydata-sphinx-theme = ">=0.16.1, <0.17"
briefcase = ">=0.3.24, <0.4"
myst-parser = ">=4.0.1, <5"
sphinxcontrib-mermaid = ">=1.0.0, <2"
twine = ">=6.2.0, <7"
psydk-gst = ">=1.24.11.post2, <2"
